### ISSUE TITLE
Image in README doesn't display on Elm packages website

### ISSUE THREAD

**Issue by KevinWMatthews** [dillonkearns/elm-cli-options-parser#1]
When viewed on the [Elm packages website](https://package.elm-lang.org/packages/dillonkearns/elm-cli-options-parser/latest/), the diagram in the README under "Options Parser Terminology" displays a raw HTML `<img>` tag instead of resolving into an image.

Seen in Firefox and Chrome on Ubuntu 18. Not sure why. The trailing slash in the tag? Unlikely but possible. The image resolves correctly if I paste the URL into either browser.

The [WebGL package](https://package.elm-lang.org/packages/elm-explorations/webgl/latest/) has both image links and static images - see the mesh rabbit.

Looks great on GitHub!

**Comment by dillonkearns** [comment]
Hey Kevin! 😄

This issue was introduced when the Elm 0.19 package server went live (https://github.com/elm/package.elm-lang.org). A change was introduced that displayed HTML as raw text. Before that, it was displayed as it is in Github... as the actual HTML tag. The reason it's using HTML is because sometimes that's needed to scale it down. I reported it, but it doesn't seem to be on the priority queue :-/

**Comment by dillonkearns** [comment]
I'll close this issue for now, I hope it gets fixed at some point!
