### ISSUE TITLE
Ellie example in readme doesn't compile

### ISSUE THREAD

**Issue by MartinSStewart** [dillonkearns/elm-cli-options-parser#6]
The [Ellie example](https://ellie-app.com/38kQTj2rhVja1) in the readme produces this compiler error 
```
too many args
Line 26, Column 5
The `config` value is not a function, but it was given 1 argument.

26|     Program.config { version = "1.2.3" }
        ^^^^^^^^^^^^^^
Are there any missing commas? Or missing parentheses?
```

**Comment by dillonkearns** [comment]
Thanks! Yeah, I really wish that Ellie had a way to use git to some how version control and update examples. I think tools like Codesandbox have that, and I'm considering setting something like that up for all my projects. It's just too much manual effort to keep Ellies up to date.

And now there's a bug in Ellie that is causing examples that were compiling previously to stop compiling when you publish new updates, which is not the intended behavior: https://github.com/ellie-app/ellie/issues/121

Here's an updated Ellie, I'll update the readme 👍 Hopefully I can find a long-term solution for my projects because it's pretty labor-intensive and prone to getting out of date now.
